### ISSUE TITLE
Error in Fedora 37 with Gnome 43.1

### ISSUE THREAD

**Issue by difrkaguilar** [jorgeajimenezl/nauta-connect-gnome-extension#2]
Description: Utility to authenticate in ETECSA network
Version: 5
Error: Requiring GXml, version none: Typelib file for namespace 'GXml' (any version) not found

**Comment by lavilao** [comment]
Installing gxml fixes it on manjaro

**Comment by jorgeajimenezl** [comment]
I am going to close this. I hope you have solved the problems
