### ISSUE TITLE
Gnome 45 Support

### ISSUE THREAD

**Issue by makecraft** [jorgeajimenezl/nauta-connect-gnome-extension#5]

**Comment by jorgeajimenezl** [comment]
Hi @makecraft. I'm finishing my thesis these days so I don't have time right now. Anyway, you can look at #4 that it is not ready yet, but it works (almost in my computer, I haven't test in another pc). Let me know if it works for ya

**Comment by makecraft** [comment]
![imagen](https://github.com/jorgeajimenezl/nauta-connect-gnome-extension/assets/117121011/10499cd3-f1d8-4783-b373-5fb6e8ae779b)
I get this string and I can't activate it

**Comment by jorgeajimenezl** [comment]
@makecraft, try to install [gxml](https://aur.archlinux.org/packages/gxml) from the AUR,  the last time that I used Manjaro pamac allowed to install from it.

**Comment by makecraft** [comment]
@jorgeajimenezl I did thanks, if there is any bug I will inform you
